apiVersion: batch/v1
kind: Job
metadata:
  name: fio-readonly
  labels:
    app: k8s-fio
spec:
  parallelism: 8
  template:
    metadata:
      labels:
        app: k8s-fio
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - k8s-fio
              topologyKey: kubernetes.io/hostname
      containers:
      - name: fio
        image: cofyc/k8s-fio:v3
        args:
        - bash
        - -c
        - "fio /jobfiles/readonly-*.fio"
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /data
          name: data
          readOnly: true
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: fio-readonly-pvc
          readOnly: true
      restartPolicy: Never
