apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-job-pvc
  labels:
    app: k8s-fio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 100Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio-job
  labels:
    app: k8s-fio
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app: k8s-fio
    spec:
      containers:
      - name: fio
        image: cofyc/k8s-fio:v1
        args:
        - fio
        - /jobfiles/readwrite.fio
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /data
          name: data
          readOnly: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: fio-job-pvc
          readOnly: false
      restartPolicy: Never
