apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-job-pvc
  labels:
    app: k8s-fio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 100Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio-job
  labels:
    app: k8s-fio
spec:
  parallelism: 1
  template:
    metadata:
      labels:
        app: k8s-fio
    spec:
      containers:
      - name: fio
        image: cofyc/k8s-fio:latest
        args:
        - fio
        - /jobfiles/readwrite.fio
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data
          name: data
          readOnly: false
        - mountPath: /jobfiles
          name: k8s-fio
          subPath: jobfiles
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: fio-job-pvc
          readOnly: false
      - name: k8s-fio
        gitRepo:
          repository: "https://github.com/cofyc/k8s-fio"
          revision: "master"
      restartPolicy: Never
