apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-readwrite-pvc
  labels:
    app: k8s-fio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-readonly-pvc
  labels:
    app: k8s-fio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph
  resources:
    requests:
      storage: 100Gi
